bcmdhd: fix -Wdeprecated-non-prototype
Fixes the warnings observed when upgrading the toolchain:

wl_cfg_btcoex.c:437:37: error: a function declaration without a
prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes]
void wl_cfg80211_btcoex_kill_handler()
                                    ^
                                     void
wl_cfg_btcoex.c:450:31: error: a function declaration without a
prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes]
void wl_cfg80211_btcoex_deinit()
                              ^
                               void
dhd_linux_platdev.c:959:34: error: a function declaration without a
prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes]
static int dhd_wifi_platform_load()
                                 ^
                                  void
dhd_log_dump.c:572:21: error: a function declaration without a prototype
is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
dhd_get_time_str_len()
                    ^
                     void
wl_cfg80211.c:20367:35: error: a function declaration without a
prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes]
uint32 wl_cfg80211_get_print_level()
                                  ^
                                   void
wl_cfg80211.c:20372:33: error: a function declaration without a
prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes]
uint32 wl_cfg80211_get_log_level()
                                ^
                                 void

Bug: 236798112
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
Change-Id: Ib9948de26185846da93bbc8df115b0b43600eb85