bcmdhd: Use correct accessor when setting a MAC address for net devices
When compiling the WLAN driver, several errors of the following nature
are emitted:

wlan/bcmdhd4389/wl_android.c:13639:18: error: passing 'const unsigned
char *' to parameter of type 'void *' discards qualifiers
[-Werror,-Wincompatible-pointer-types-discards-qualifiers]
                (void)memcpy_s(new_ndev->dev_addr, ETH_ALEN, addr,
		ETH_ALEN);

wlan/bcmdhd4389/include/bcmstdlib_s.h:31:27: note: passing argument to
parameter 'dest' here
extern int memcpy_s(void *dest, size_t destsz, const void *src, size_t
n);

This is because the dev_addr field is not meant to be used directly for
setting up a MAC address. Instead, MAC addresses should be modified
through the dev_addr_* family of functions to guarantee that the kernel
can update the RB tree layout it uses for maintaining a device's
addresses.

Commit d07b26f5bbea ("dev_addr: add a modification check")
goes a step further in enforcing this by emitting a warning as such:

[   55.287668] netdevice: aware_nmi0: Incorrect netdev->dev_addr
[   55.287706] WARNING: CPU: 0 PID: 782 at net/core/dev_addr_lists.c:517 dev_addr_check+0xf8/0x124
[   55.288185] CPU: 0 PID: 782 Comm: wifi_ext@1.0-se Tainted: G        W  OE     5.16.0-mainline-g54df59a346b6 #1
[   55.288191] Hardware name: Oriole EVT 1.1 (DT)
[   55.288195] pstate: 60400005 (nZCv daif +PAN -UAO -TCO -DIT -SSBS BTYPE=--)
[   55.288201] pc : dev_addr_check+0xf8/0x124
[   55.288208] lr : dev_addr_check+0xf8/0x124
[   55.288214] sp : ffffffc013c4ba80
[   55.288217] x29: ffffffc013c4ba80 x28: 0000000000000000 x27: 0000000000000000
[   55.288226] x26: ffffffc013c4bc80 x25: 0000000000000000 x24: 0000000000008914
[   55.288234] x23: 0000000000000001 x22: 0000000000001002 x21: ffffffe7f75ab160
[   55.288242] x20: ffffff8807da5000 x19: ffffff8807da5000 x18: ffffffc0111c1070
[   55.288251] x17: 3020303020303020 x16: 00000000000000d8 x15: ffffffe7f3c2627c
[   55.288259] x14: ffffffe7f54f6400 x13: 0a726464615f7665 x12: 0000000000000018
[   55.288266] x11: 00000000ffffffff x10: 0000000100000001 x9 : b0446e1c2178d100
[   55.288274] x8 : b0446e1c2178d100 x7 : 6474656e20746365 x6 : 72726f636e49203a
[   55.288281] x5 : ffffff893298542a x4 : ffffffe7f532b7f1 x3 : ffff0a00ffffff04
[   55.288289] x2 : 0000000000000001 x1 : 0000000000000000 x0 : 0000000000000031
[   55.288297] Call trace:
[   55.288299] dev_addr_check+0xf8/0x124
[   55.288306] __dev_open+0x58/0x2ac
[   55.288314] __dev_change_flags+0xcc/0x228
[   55.288320] dev_change_flags+0x28/0x6c
[   55.288325] devinet_ioctl+0x2cc/0x5b4
[   55.288334] inet_ioctl+0xb8/0x1f4
[   55.288339] sock_do_ioctl+0x78/0x184
[   55.288347] sock_ioctl+0x484/0x6bc
[   55.288352] __arm64_sys_ioctl+0xa8/0x118
[   55.288360] invoke_syscall+0x64/0x178
[   55.288368] el0_svc_common+0xb8/0x100
[   55.288373] do_el0_svc+0x28/0xa0
[   55.288377] el0_svc+0x24/0x84
[   55.288386] el0t_64_sync_handler+0x88/0xec
[   55.288391] el0t_64_sync+0x1b4/0x1b8

Thus, use the dev_addr_* set of functions to properly update the MAC
address for a device.

Bug: 217483442
Signed-off-by: Isaac J. Manjarres <isaacmanjarres@google.com>
Change-Id: Idb152176aa2f0ba40a683e2d6cca339fcc17e66d